import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8')

test('flash sale uses a dedicated endpoint and keeps its business source through checkout', () => {
  const api = read('../src/api/shop.js')
  const page = read('../src/views/FlashSaleView.vue')
  const checkout = read('../src/views/CheckoutView.vue')
  assert.match(api, /flash-sales\/\$\{activityId\}\/orders/)
  assert.match(page, /businessType: 'FLASH_SALE'/)
  assert.match(page, /businessSourceId: row\.activity\.id/)
  assert.match(checkout, /submitFlashSaleOrder\(businessSourceId/)
})

test('live square and new arrivals use real public APIs and controlled routes', () => {
  const api = read('../src/api/shop.js')
  const home = read('../src/views/HomeView.vue')
  const liveSquare = read('../src/views/LiveSquareView.vue')
  const router = read('../src/router/index.js')
  const liveRoom = read('../src/views/LiveRoomView.vue')
  assert.match(api, /\/shop\/live-rooms/)
  assert.match(api, /\/shop\/new-arrivals/)
  assert.match(api, /\/shop\/brand-culture/)
  assert.match(api, /\/shop\/live-reservations/)
  assert.match(api, /live-rooms\/\$\{id\}\/reservation/)
  assert.match(home, /module\.type === 'live'/)
  assert.match(home, /module\.type === 'newArrivals'/)
  assert.doesNotMatch(home, /mod\.type === 'discovery'/)
  assert.match(home, /class="home-feature-row"/)
  assert.match(home, /visibleFeatureModules/)
  assert.match(home, /liveRooms\.slice\(0, 1\)/)
  assert.match(home, /newArrivals\.slice\(0, 1\)/)
  assert.match(router, /path: '\/live'/)
  assert.match(router, /path: '\/new-arrivals'/)
  assert.match(router, /path: '\/brand-culture'/)
  assert.match(liveRoom, /url\.protocol !== 'https:'/)
  assert.match(liveSquare, /displayConfig\?\.liveSquareEnabled/)
  assert.match(liveSquare, /activeTab === 'live'/)
  assert.match(liveSquare, /activeTab === 'upcoming'/)
  assert.match(liveSquare, /直播广场暂未开放/)
  assert.match(liveSquare, /toggleReservation/)
  assert.match(liveSquare, /item\.products\?\.slice\(0, 2\)/)
  assert.match(home, /campaign-feed/)
  assert.match(home, /campaignCountdown/)
  assert.match(home, /campaignActivity\(product\)/)
  assert.match(home, /listFlashSales/)
})

test('new arrivals and brand culture respect independent page switches', () => {
  const arrivals = read('../src/views/NewArrivalsView.vue')
  const culture = read('../src/views/BrandCultureView.vue')
  const app = read('../src/App.vue')
  assert.match(arrivals, /displayConfig\?\.newArrivalsEnabled/)
  assert.match(arrivals, /新品页面暂未开放/)
  assert.match(culture, /!culture\.enabled/)
  assert.match(culture, /white-space:pre-line/)
  assert.doesNotMatch(culture, /v-html/)
  assert.match(culture, /culture\.detailImages\?\.length/)
  assert.match(culture, /v-for="\(image, index\) in culture\.detailImages"/)
  assert.match(culture, /loading="lazy"/)
  assert.match(culture, /v-else-if="culture\.content"/)
  assert.match(culture, /width:100%;height:auto/)
  assert.match(culture, /display:block;width:100%;height:auto/)
  assert.match(app, /v-if="brandCultureEnabled" to="\/brand-culture"/)
})

test('public storefront excludes repurchase pages and rejects non-public checkout modes', () => {
  const router = read('../src/router/index.js')
  const policy = read('../src/surfaces/public/commercePolicy.js')
  assert.doesNotMatch(router, /RepurchaseView|\/repurchase/)
  assert.match(policy, /new Set\(\['NORMAL', 'FLASH_SALE'\]\)/)
  assert.doesNotMatch(policy, /REPURCHASE|\/repurchase|复购/)
})

test('optional business entries only render when enabled by tenant configuration', () => {
  const home = read('../src/views/HomeView.vue')
  const publicPolicy = read('../src/surfaces/public/commercePolicy.js')
  const integratedPolicy = read('../src/surfaces/integrated/commercePolicy.js')
  assert.match(home, /resolveBusinessEntries\(home\.value\.businessConfig/)
  assert.match(publicPolicy, /config\.flashSaleEnabled/)
  assert.doesNotMatch(publicPolicy, /config\.repurchaseMallEnabled|\/repurchase|复购/)
  assert.match(integratedPolicy, /config\.repurchaseMallEnabled/)
  assert.match(integratedPolicy, /path: '\/repurchase'/)
  assert.match(home, /v-if="businessEntries\.length"/)
})

test('public, team, and integrated H5 surfaces use controlled route trees and build outputs', () => {
  const publicRouter = read('../src/router/index.js')
  const teamRouter = read('../src/surfaces/team/router.js')
  const integratedRouter = read('../src/surfaces/integrated/router.js')
  const vite = read('../vite.config.js')
  const packageJson = JSON.parse(read('../package.json'))
  assert.doesNotMatch(publicRouter, /InviteView|TeamPerformanceView|@\/views\/WalletView/)
  assert.match(publicRouter, /PublicWalletView/)
  assert.match(teamRouter, /InviteView/)
  assert.match(teamRouter, /TeamPerformanceView/)
  assert.match(teamRouter, /WalletView/)
  assert.match(integratedRouter, /HomeView/)
  assert.match(integratedRouter, /RepurchaseView/)
  assert.match(integratedRouter, /InviteView/)
  assert.match(integratedRouter, /TeamPerformanceView/)
  assert.match(integratedRouter, /IntegratedWalletView/)
  assert.doesNotMatch(teamRouter, /BalanceTransferView|\/profile\/wallet\/transfer/)
  assert.match(integratedRouter, /BalanceTransferView/)
  assert.match(integratedRouter, /restoreShopSession\('integrated'\)/)
  assert.match(vite, /dist-team/)
  assert.match(vite, /dist-integrated/)
  assert.equal(packageJson.scripts['build:public'].includes('check:public-surface'), true)
  assert.equal(packageJson.scripts['build:team'].includes('check:team-surface'), true)
  assert.equal(packageJson.scripts['build:integrated'].includes('check:integrated-surface'), true)
})
