import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8')

test('flash sale uses a dedicated endpoint and keeps its business source through checkout', () => {
  const api = read('../src/api/shop.js')
  const page = read('../src/views/FlashSaleView.vue')
  const checkout = read('../src/views/CheckoutView.vue')
  assert.match(api, /flash-sales\/\$\{activityId\}\/orders/)
  assert.match(page, /businessType: 'FLASH_SALE'/)
  assert.match(page, /businessSourceId: row\.activity\.id/)
  assert.match(checkout, /submitFlashSaleOrder\(businessSourceId/)
})

test('live square and new arrivals use real public APIs and controlled routes', () => {
  const api = read('../src/api/shop.js')
  const home = read('../src/views/HomeView.vue')
  const router = read('../src/router/index.js')
  const liveRoom = read('../src/views/LiveRoomView.vue')
  assert.match(api, /\/shop\/live-rooms/)
  assert.match(api, /\/shop\/new-arrivals/)
  assert.match(home, /mod\.type === 'discovery'/)
  assert.match(home, /liveRooms\.value\.length > 0 \|\| newArrivals\.value\.length > 0/)
  assert.match(router, /path: '\/live'/)
  assert.match(router, /path: '\/new-arrivals'/)
  assert.match(liveRoom, /url\.protocol !== 'https:'/)
  assert.match(home, /campaign-feed/)
  assert.match(home, /campaignCountdown/)
  assert.match(home, /campaignActivity\(product\)/)
  assert.match(home, /listFlashSales/)
})

test('public storefront excludes repurchase pages and rejects non-public checkout modes', () => {
  const router = read('../src/router/index.js')
  const policy = read('../src/surfaces/public/commercePolicy.js')
  assert.doesNotMatch(router, /RepurchaseView|\/repurchase/)
  assert.match(policy, /new Set\(\['NORMAL', 'FLASH_SALE'\]\)/)
  assert.doesNotMatch(policy, /REPURCHASE|\/repurchase|复购/)
})

test('optional business entries only render when enabled by tenant configuration', () => {
  const home = read('../src/views/HomeView.vue')
  const publicPolicy = read('../src/surfaces/public/commercePolicy.js')
  const integratedPolicy = read('../src/surfaces/integrated/commercePolicy.js')
  assert.match(home, /resolveBusinessEntries\(home\.value\.businessConfig/)
  assert.match(publicPolicy, /config\.flashSaleEnabled/)
  assert.doesNotMatch(publicPolicy, /config\.repurchaseMallEnabled|\/repurchase|复购/)
  assert.match(integratedPolicy, /config\.repurchaseMallEnabled/)
  assert.match(integratedPolicy, /path: '\/repurchase'/)
  assert.match(home, /v-if="businessEntries\.length"/)
})

test('public, team, and integrated H5 surfaces use controlled route trees and build outputs', () => {
  const publicRouter = read('../src/router/index.js')
  const teamRouter = read('../src/surfaces/team/router.js')
  const integratedRouter = read('../src/surfaces/integrated/router.js')
  const vite = read('../vite.config.js')
  const packageJson = JSON.parse(read('../package.json'))
  assert.doesNotMatch(publicRouter, /InviteView|TeamPerformanceView|WalletView/)
  assert.match(teamRouter, /InviteView/)
  assert.match(teamRouter, /TeamPerformanceView/)
  assert.match(teamRouter, /WalletView/)
  assert.match(integratedRouter, /HomeView/)
  assert.match(integratedRouter, /RepurchaseView/)
  assert.match(integratedRouter, /InviteView/)
  assert.match(integratedRouter, /TeamPerformanceView/)
  assert.match(integratedRouter, /WalletView/)
  assert.match(integratedRouter, /restoreShopSession\('integrated'\)/)
  assert.match(vite, /dist-team/)
  assert.match(vite, /dist-integrated/)
  assert.equal(packageJson.scripts['build:public'].includes('check:public-surface'), true)
  assert.equal(packageJson.scripts['build:integrated'].includes('check:integrated-surface'), true)
})
