<template>
  <div class="page-container">
    <div class="page-heading"><div><h2>商户货款</h2><p>成本结算、售后冲回、发票登记和人工打款留痕。</p></div><el-button v-if="canManage" type="primary" @click="openApply">代商户申请提现</el-button></div>
    <el-alert title="系统不自动计算税费。需要少打款时使用“调整金额（负数）+ 调整原因”，发票金额与实际打款分别留痕。" type="warning" :closable="false" show-icon />
    <el-tabs v-model="tab" @tab-change="loadCurrent">
      <el-tab-pane label="货款账户" name="accounts"><el-table :data="accounts" v-loading="loading" stripe><el-table-column prop="merchantName" label="商户" min-width="180"/><el-table-column prop="pendingAmount" label="待结算"/><el-table-column prop="availableAmount" label="可提现"/><el-table-column prop="frozenAmount" label="提现冻结"/><el-table-column prop="debtAmount" label="退款欠款"/><el-table-column prop="totalPaidAmount" label="累计已打款"/></el-table></el-tab-pane>
      <el-tab-pane label="订单货款明细" name="settlements"><el-table :data="settlements" v-loading="loading" stripe><el-table-column prop="merchantName" label="商户"/><el-table-column prop="orderNo" label="订单号" min-width="190"/><el-table-column prop="quantity" label="数量"/><el-table-column prop="costAmount" label="成本单价"/><el-table-column prop="settlementAmount" label="应结货款"/><el-table-column prop="reversedAmount" label="已冲回"/><el-table-column prop="status" label="状态"/></el-table></el-tab-pane>
      <el-tab-pane label="提现、发票与打款" name="withdrawals"><el-table :data="withdrawals" v-loading="loading" stripe><el-table-column prop="withdrawalNo" label="申请单号" min-width="190"/><el-table-column prop="merchantName" label="商户"/><el-table-column prop="requestedAmount" label="申请金额"/><el-table-column prop="invoiceRequiredAmount" label="应开票"/><el-table-column prop="invoiceReceivedAmount" label="已收票"/><el-table-column prop="adjustmentAmount" label="调整"/><el-table-column prop="actualPaidAmount" label="实付"/><el-table-column prop="status" label="状态"/><el-table-column v-if="canManage" label="操作" width="210"><template #default="{ row }"><el-button v-if="['SUBMITTED','INVOICE_PENDING','READY_TO_PAY'].includes(row.status)" link type="primary" @click="openReview(row)">发票/审核</el-button><el-button v-if="row.status==='READY_TO_PAY'" link type="success" @click="openPay(row)">确认打款</el-button><el-button v-if="['SUBMITTED','INVOICE_PENDING','READY_TO_PAY'].includes(row.status)" link type="danger" @click="reject(row)">驳回</el-button></template></el-table-column></el-table></el-tab-pane>
    </el-tabs>
    <el-dialog v-model="applyVisible" title="代商户申请提现" width="520px"><el-form label-width="100px"><el-form-item label="商户" required><el-select v-model="applyForm.merchantId" filterable style="width:100%"><el-option v-for="item in merchants" :key="item.id" :label="item.merchantName" :value="item.id" /></el-select></el-form-item><el-form-item label="申请金额" required><el-input-number v-model="applyForm.requestedAmount" :min="0.01" :precision="2" style="width:100%" /></el-form-item></el-form><template #footer><el-button @click="applyVisible=false">取消</el-button><el-button type="primary" @click="submitApply">提交</el-button></template></el-dialog>
    <el-dialog v-model="reviewVisible" title="登记发票与打款调整" width="600px"><el-form label-width="120px"><el-form-item label="应开票金额"><el-input-number v-model="reviewForm.invoiceRequiredAmount" :min="0" :precision="2" style="width:100%" /></el-form-item><el-form-item label="已收票金额"><el-input-number v-model="reviewForm.invoiceReceivedAmount" :min="0" :precision="2" style="width:100%" /></el-form-item><el-form-item label="发票状态"><el-select v-model="reviewForm.invoiceStatus" style="width:100%"><el-option label="无需发票" value="NOT_REQUIRED"/><el-option label="待收发票" value="PENDING"/><el-option label="已收发票" value="RECEIVED"/></el-select></el-form-item><el-form-item label="调整金额"><el-input-number v-model="reviewForm.adjustmentAmount" :max="0" :precision="2" style="width:100%"/><div class="help">少打100元填写 -100；不自动认定为税费。</div></el-form-item><el-form-item label="调整原因"><el-input v-model="reviewForm.adjustmentReason" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="reviewVisible=false">取消</el-button><el-button type="primary" @click="submitReview">保存审核</el-button></template></el-dialog>
    <el-dialog v-model="payVisible" title="确认实际打款" width="520px"><el-form label-width="110px"><el-form-item label="实际打款"><el-input-number v-model="payForm.actualPaidAmount" :min="0.01" :precision="2" style="width:100%"/></el-form-item><el-form-item label="银行流水号"><el-input v-model="payForm.paymentReference" /></el-form-item><el-form-item label="凭证地址"><el-input v-model="payForm.paymentVoucherUrl" /></el-form-item></el-form><template #footer><el-button @click="payVisible=false">取消</el-button><el-button type="primary" @click="submitPay">确认已打款</el-button></template></el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useAppStore } from '@/store'
import { applyMerchantWithdrawal, listMerchantAccounts, listMerchantSettlements, listMerchants, listMerchantWithdrawals, payMerchantWithdrawal, rejectMerchantWithdrawal, reviewMerchantWithdrawal } from '@/api/merchant'
const store=useAppStore(); const canManage=computed(()=>store.hasPermission('finance:manage')); const tab=ref('accounts'); const loading=ref(false)
const merchants=ref([]); const accounts=ref([]); const settlements=ref([]); const withdrawals=ref([])
const applyVisible=ref(false); const reviewVisible=ref(false); const payVisible=ref(false); const current=ref(null)
const applyForm=ref({merchantId:null,requestedAmount:0}); const reviewForm=ref({invoiceRequiredAmount:0,invoiceReceivedAmount:0,invoiceStatus:'NOT_REQUIRED',adjustmentAmount:0,adjustmentReason:''}); const payForm=ref({actualPaidAmount:0,paymentReference:'',paymentVoucherUrl:''})
const loadCurrent=async()=>{loading.value=true;try{if(tab.value==='accounts')accounts.value=(await listMerchantAccounts()).data||[];if(tab.value==='settlements')settlements.value=(await listMerchantSettlements()).data||[];if(tab.value==='withdrawals')withdrawals.value=(await listMerchantWithdrawals()).data||[]}finally{loading.value=false}}
const openApply=()=>{applyForm.value={merchantId:null,requestedAmount:0};applyVisible.value=true}
const submitApply=async()=>{await applyMerchantWithdrawal(applyForm.value);ElMessage.success('提现申请已提交');applyVisible.value=false;tab.value='withdrawals';await loadCurrent()}
const openReview=(row)=>{current.value=row;reviewForm.value={invoiceRequiredAmount:Number(row.invoiceRequiredAmount||0),invoiceReceivedAmount:Number(row.invoiceReceivedAmount||0),invoiceStatus:row.invoiceStatus||'NOT_REQUIRED',adjustmentAmount:Number(row.adjustmentAmount||0),adjustmentReason:row.adjustmentReason||''};reviewVisible.value=true}
const submitReview=async()=>{await reviewMerchantWithdrawal(current.value.id,reviewForm.value);ElMessage.success('发票与审核信息已保存');reviewVisible.value=false;await loadCurrent()}
const openPay=(row)=>{current.value=row;payForm.value={actualPaidAmount:Number(row.requestedAmount||0)+Number(row.adjustmentAmount||0),paymentReference:'',paymentVoucherUrl:''};payVisible.value=true}
const submitPay=async()=>{await payMerchantWithdrawal(current.value.id,payForm.value);ElMessage.success('打款已确认');payVisible.value=false;await loadCurrent()}
const reject=async(row)=>{const {value}=await ElMessageBox.prompt('请填写驳回原因','驳回商户提现',{inputValidator:(v)=>Boolean(v?.trim())||'必须填写原因'});await rejectMerchantWithdrawal(row.id,{reason:value});ElMessage.success('已驳回；冻结金额已先抵退款欠款，剩余部分退回可提现余额');await loadCurrent()}
onMounted(async()=>{merchants.value=(await listMerchants({status:1})).data||[];await loadCurrent()})
</script>
<style scoped>.page-heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:16px}.page-heading h2{margin:0}.page-heading p{margin:6px 0 0;color:#909399}.help{color:#909399;font-size:12px;margin-top:6px}</style>
