<template>
  <div class="page"><div class="intro"><div><h2>消息运营</h2><p>个人消息与商城公告相互独立；模板修改只影响未来消息。</p></div><el-tag type="warning">外部通道生产默认关闭</el-tag></div>
  <el-tabs v-model="tab">
    <el-tab-pane label="消息模板" name="templates"><el-table :data="templates" stripe><el-table-column prop="category" label="分类" width="150"/><el-table-column prop="eventType" label="触发事件" width="190"/><el-table-column prop="titleTemplate" label="标题快照模板"/><el-table-column prop="version" label="版本" width="70"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.enabled===1?'success':'info'">{{row.enabled===1?'启用':'关闭'}}</el-tag></template></el-table-column><el-table-column label="操作" width="90"><template #default="{row}"><el-button link type="primary" @click="edit(row)">维护</el-button></template></el-table-column></el-table></el-tab-pane>
    <el-tab-pane label="事件与渠道" name="channels"><el-alert title="短信、App 推送、小程序订阅消息需客户账号、模板审核和授权资料；当前不能开启，也不会真实发送。" type="warning" :closable="false"/><el-table :data="channels" stripe><el-table-column prop="eventType" label="触发事件"/><el-table-column label="站内消息" width="130"><template #default="{row}"><el-switch :model-value="row.inAppEnabled===1" @change="v=>toggle(row,v)"/></template></el-table-column><el-table-column label="短信" width="100"><el-tag type="info">关闭</el-tag></el-table-column><el-table-column label="App 推送" width="110"><el-tag type="info">关闭</el-tag></el-table-column><el-table-column label="小程序订阅" width="120"><el-tag type="info">关闭</el-tag></el-table-column><el-table-column label="短信估算成本" width="130"><template #default="{row}">¥{{Number(row.estimatedSmsCost||0).toFixed(4)}}</template></el-table-column></el-table></el-tab-pane>
    <el-tab-pane label="发送记录" name="deliveries"><el-table :data="deliveries" stripe><el-table-column prop="messageId" label="消息编号"/><el-table-column prop="channel" label="渠道"/><el-table-column prop="status" label="状态"/><el-table-column prop="retryCount" label="重试次数"/><el-table-column prop="estimatedCost" label="估算成本"/><el-table-column prop="errorCode" label="脱敏失败原因"/><el-table-column prop="createTime" label="记录时间"/></el-table><el-pagination v-model:current-page="pageNum" :page-size="20" :total="total" layout="prev,pager,next,total" @current-change="loadDeliveries"/></el-tab-pane>
  </el-tabs>
  <el-dialog v-model="dialog" title="维护未来消息模板" width="620px"><el-form label-position="top"><el-form-item label="标题"><el-input v-model="form.titleTemplate" maxlength="128" show-word-limit/></el-form-item><el-form-item label="列表摘要（不得含金额、卡号、地址、手机号、退款原因或验证码）"><el-input v-model="form.summaryTemplate" maxlength="300" show-word-limit/></el-form-item><el-form-item label="正文"><el-input v-model="form.contentTemplate" type="textarea" :rows="5" maxlength="1000" show-word-limit/></el-form-item><el-form-item label="启用"><el-switch v-model="form.enabled" :active-value="1" :inactive-value="0"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存未来模板</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import{onMounted,ref}from'vue';import{ElMessage}from'element-plus';import{listMessageTemplates,updateMessageTemplate,listMessageChannels,updateInAppChannel,listMessageDeliveries}from'@/api/messageOperation'
const tab=ref('templates'),templates=ref([]),channels=ref([]),deliveries=ref([]),pageNum=ref(1),total=ref(0),dialog=ref(false),form=ref({})
const load=async()=>{const [t,c]=await Promise.all([listMessageTemplates(),listMessageChannels()]);templates.value=t.data||[];channels.value=c.data||[]}
const loadDeliveries=async()=>{const r=(await listMessageDeliveries({pageNum:pageNum.value,pageSize:20})).data||{};deliveries.value=r.list||[];total.value=Number(r.total||0)}
const edit=row=>{form.value={...row};dialog.value=true}
const save=async()=>{await updateMessageTemplate(form.value.id,form.value);dialog.value=false;ElMessage.success('已保存，仅影响未来生成的消息');await load()}
const toggle=async(row,value)=>{await updateInAppChannel(row.id,value);ElMessage.success(value?'站内消息已启用':'站内消息已关闭');await load()}
onMounted(()=>{load();loadDeliveries()})
</script>
<style scoped>.page{padding:20px}.intro{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;padding:18px;background:#fff;border-radius:12px}.intro h2{margin:0 0 6px}.intro p{margin:0;color:#667085}.el-alert{margin-bottom:14px}.el-pagination{justify-content:flex-end;margin-top:14px}</style>
