CREATE TABLE IF NOT EXISTS `dms_line_change_application` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `apply_no` varchar(64) NOT NULL,
  `agent_id` bigint NOT NULL,
  `old_parent_agent_id` bigint DEFAULT NULL,
  `new_parent_agent_id` bigint NOT NULL,
  `reason` varchar(500) NOT NULL,
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '0待审核 1已通过待生效 2已拒绝 3已执行',
  `applicant_id` bigint NOT NULL,
  `applicant_name` varchar(64) NOT NULL,
  `auditor_id` bigint DEFAULT NULL,
  `auditor_name` varchar(64) DEFAULT NULL,
  `audit_remark` varchar(500) DEFAULT NULL,
  `effective_time` datetime NOT NULL,
  `before_snapshot` json NOT NULL,
  `after_snapshot` json DEFAULT NULL,
  `audit_time` datetime DEFAULT NULL,
  `execute_time` datetime DEFAULT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_apply_no` (`apply_no`),
  KEY `idx_agent_status` (`agent_id`,`status`),
  KEY `idx_status_effective` (`status`,`effective_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='整线迁移申请、双人审核与关系快照';
